/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
export type Activity = {
  id: string;
  courseCode: string;
  /**
   * @format int32
   */
  week: number;
  /**
   * @format date-time
   */
  start: string;
  /**
   * @format date-time
   */
  end: string;
  title: string;
  summary: string;
  staffMembers: StaffMember[];
  studentGroups: string[];
  rooms: Room[];
};

export type CalendarQuery = {
  identifier: CourseIdentifier;
  studentGroups: string[];
};

export type Course = {
  name: string;
  /**
   * @format int32
   */
  amountOfTerms: number;
};

export type CourseIdentifier = {
  courseCode: string;
  /**
   * @format int32
   */
  courseTerm: number;
  semester: string;
};

export type Room = {
  name: string;
  buildingName: string;
  url: string;
};

export type Semester = {
  name: string;
};

export type SemestersWithCurrent = {
  semesters: {
    [key: string]: Semester;
  };
  currentSemester: string;
};

export type StaffMember = {
  firstName: string;
  lastName: string;
};
