// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CourseIdentifier } from "./CourseIdentifier";

export interface CalendarQuery { identifier: CourseIdentifier, studentGroups: Array<string>, }