// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CourseIdentifier { courseCode: string, courseTerm: number, semester: string, }