// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Semester } from "./Semester";

export interface SemestersWithCurrent { semesters: Record<string, Semester>, currentSemester: string, }