[package]
name = "ntnu-timeplan-shared"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
ts-rs = { version = "6.2", features = ["serde-compat", "chrono-impl"] }
