// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "activities", input: ActivitiesQuery, result: Activity[] } | 
        { key: "courses", input: never, result: { [key: string]: Course } } | 
        { key: "encode-calendar-query", input: CalendarQuery[], result: string } | 
        { key: "semesters", input: never, result: SemestersWithCurrent },
    mutations: never,
    subscriptions: never
};

export type SemestersWithCurrent = { semesters: { [key: string]: Semester }; currentSemester: string }

export type ActivitiesQuery = { courseCode: string; courseTerm: number; semester: string }

export type CourseIdentifier = { courseCode: string; courseTerm: number; semester: string }

export type CalendarQuery = { identifier: CourseIdentifier; studentGroups: string[] }

export type Course = { name: string; amountOfTerms: number }

export type StaffMember = { firstName: string; lastName: string }

export type Activity = { id: string; courseCode: string; week: number; start: string; end: string; title: string; summary: string; staffMembers: StaffMember[]; studentGroups: string[]; rooms: Room[] }

export type Semester = { name: string }

export type Room = { name: string; buildingName: string; url: string }
