[package]
name = "ntnu-timeplan-api"
version = "0.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.22", features = ["full"] }
anyhow = "1.0"
scraper = "0.14.0"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
time = "0.3"
itertools = "0.10"
shrinkwraprs = "0.3"
icalendar = "0.15"
derive_more = "0.99"
axum = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"
mini-moka = "0.10.0"
futures = "0.3"
async-graphql = "5.0"
async-graphql-axum = "5.0"
