[package]
name = "ntnu-timeplan-api"
version = "0.0.0"
edition = "2021"

[dependencies]
ntnu-timeplan-shared = { path = "../shared" }

tokio = { version = "1.22", features = ["full"] }
anyhow = "1.0"
scraper = "0.14.0"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
time = "0.3"
itertools = "0.10"
axum = "0.6"
axum-macros = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
mini-moka = "0.10"
tower = "0.4"
tower_governor = "0.0.4"
serde_qs = "0.12"
icalendar = "0.15"
